Updated the "fog" gem in "elasticsearch::ebs" recipe to 1.21.0
I had some errors when running the cookbook as, it turned out, I didn't set the AWS region correctly.
Fog (version 1.12.1) returns a null instance for aws when the region is incorrect with no verbose debug information when this occurs:

    NoMethodError: ruby_block[Create EBS volume on /dev/sda2 (size: 25GB)] (elasticsearch::ebs line 16) had an error: NoMethodError: undefined method `volumes' for nil:NilClass
    /var/chef-solo/cookbooks/elasticsearch/libraries/create_ebs.rb:41:in `block (2 levels) in create_ebs'

Instead with the latest version it was able to show the issue more explicitly:

    ArgumentError
    -------------
    Unknown region: "us-west-2b"

Closes #200