Declare `node.elasticsearch` defensively in attributes/default.rb
In some environments, the cookbook blew Chef run since the `node.elasticsearch` attribute wasn't set:

    ================================================================================
    Recipe Compile Error in /tmp/chef-solo/cookbooks/elasticsearch/attributes/proxy.rb
    ================================================================================

    NoMethodError
    -------------
    undefined method `to_hash' for nil:NilClass

    Cookbook Trace:
    ---------------
      /tmp/chef-solo/cookbooks/elasticsearch/attributes/default.rb:8:in `from_file'
      /tmp/chef-solo/cookbooks/elasticsearch/attributes/proxy.rb:1:in `from_file'

    Relevant File Content:
    ----------------------
    /tmp/chef-solo/cookbooks/elasticsearch/attributes/default.rb:

      1:  # Load settings from data bag 'elasticsearch/settings'
      2:  #
      3:  settings = Chef::DataBagItem.load('elasticsearch', 'settings') rescue {}
      4:  Chef::Log.debug "Loaded settings: #{settings.inspect}"
      5:
      6:  # Initialize the node attributes with node attributes merged with data bag attributes
      7:  #
      8>> node.set[:elasticsearch] = DeepMerge.merge(node[:elasticsearch].to_hash, settings.to_hash)

Fixes #58