Add dependency on the "xml" cookbook because of the "elasticsearch::create_ebs"
The `create_ebs` helper method uses the Fog gem to work with the Amazon API.
Fog depends on Nokogiri, which can't be installed without the libxml bindings:

    Building native extensions.  This could take a while...
    ERROR:  Error installing fog:
        ERROR: Failed to build gem native extension.

            /opt/chef/embedded/bin/ruby extconf.rb
    checking for libxml/parser.h... *** extconf.rb failed ***

Chances are, your system already has libxml installed. If not, just add
the "xml" cookbook to the runlist.